CREATE TABLE app_user (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;   
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_app_user_updated_at_column
BEFORE UPDATE on app_user
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();